name: pytorch_gpu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - cryptography=38.0.1=py39h21b164f_0
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=12.0.76=0
  - cuda-documentation=12.0.76=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.0.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=12.0.76=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=12.0.90=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=12.0.90=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=12.0.90=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - cudatoolkit=11.3.1=h59b6b97_2
  - freetype=2.10.4=hd328e21_0
  - idna=3.4=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9d=h2bbff1b_0
  - libcublas=12.0.1.189=0
  - libcublas-dev=12.0.1.189=0
  - libcufft=11.0.0.21=0
  - libcufft-dev=11.0.0.21=0
  - libcurand=10.3.1.50=0
  - libcurand-dev=10.3.1.50=0
  - libcusolver=11.4.2.57=0
  - libcusolver-dev=11.4.2.57=0
  - libcusparse=12.0.0.76=0
  - libcusparse-dev=12.0.0.76=0
  - libnpp=12.0.0.30=0
  - libnpp-dev=12.0.0.30=0
  - libnvjpeg=12.0.0.28=0
  - libnvjpeg-dev=12.0.0.28=0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - nsight-compute=2022.4.0.15=0
  - numpy-base=1.21.2=py39h0829f74_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1s=h2bbff1b_0
  - pip=21.2.4=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - pytorch-cuda=11.7=h67b0de4_0
  - pytorch-mutex=1.0=cuda
  - requests=2.28.1=py39haa95532_0
  - setuptools=58.0.4=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=h2bbff1b_0
  - tk=8.6.11=h2bbff1b_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.13=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h8cc25b3_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.33.0
    - aiohappyeyeballs==2.3.4
    - aiohttp==3.10.0
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==4.4.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - axial-positional-embedding==0.2.1
    - biopandas==0.4.1
    - biopython==1.81
    - blis==0.7.11
    - bottleneck==1.3.5
    - cachetools==5.3.2
    - catalogue==2.0.10
    - charset-normalizer==2.1.1
    - click==8.1.7
    - cloudpathlib==0.16.0
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - colt5-attention==0.10.14
    - comm==0.2.2
    - confection==0.1.4
    - cycler==0.11.0
    - cymem==2.0.8
    - cython==3.0.5
    - debugpy==1.8.1
    - decorator==5.1.1
    - deprecated==1.2.13
    - dgl==2.0.0
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - dtaidistance==2.3.4
    - einops==0.6.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastai==2.7.14
    - fastcore==1.5.29
    - fastdownload==0.0.7
    - fastprogress==1.0.3
    - filelock==3.13.1
    - fonttools==4.28.5
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - ftfy==6.1.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.23.3
    - google-auth-oauthlib==1.1.0
    - grpcio==1.59.0
    - h11==0.14.0
    - h5py==3.7.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.24.5
    - imbalanced-learn==0.12.0
    - importlib-metadata==6.8.0
    - ipykernel==6.29.3
    - ipython==8.18.1
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.2.0
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - lazy-loader==0.3
    - liac-arff==2.5.0
    - lightning-utilities==0.11.6
    - llvmlite==0.39.1
    - local-attention==1.8.6
    - markdown==3.5
    - markupsafe==2.1.3
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.6
    - mne==0.20.7
    - modelscope==1.16.1
    - mpmath==1.3.0
    - multidict==6.0.5
    - murmurhash==1.0.10
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - numba==0.56.4
    - numpy==1.22.4
    - oauthlib==3.2.2
    - openai==0.28.0
    - openpyxl==3.0.10
    - packaging==21.3
    - pandas==1.3.5
    - parso==0.8.3
    - path==16.7.1
    - patsy==0.5.3
    - pillow==9.0.0
    - platformdirs==4.2.0
    - pooch==1.8.1
    - preshed==3.0.9
    - product-key-memory==0.2.9
    - prompt-toolkit==3.0.43
    - protobuf==4.23.4
    - psutil==5.9.7
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==2.6.4
    - pydantic-core==2.16.3
    - pygments==2.17.2
    - pynndescent==0.5.8
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - python-utils==3.1.0
    - pyts==0.12.0
    - pytz==2021.3
    - pywavelets==1.3.0
    - pywin32==306
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - rarfile==4.0
    - rdkit==2023.9.5
    - reformer-pytorch==1.4.4
    - regex==2023.8.8
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safetensors==0.4.2
    - scikit-learn==1.4.1.post1
    - scikit-posthocs==0.7.0
    - scipy==1.7.3
    - seaborn==0.11.2
    - sentencepiece==0.2.0
    - sentry-sdk==1.45.0
    - setproctitle==1.3.3
    - skorch==0.15.0
    - sktime==0.12.1
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - spacy==3.7.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - statsmodels==0.13.5
    - stumpy==1.12.0
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.15.0
    - tensorboard-data-server==0.7.2
    - thinc==8.2.3
    - thop==0.1.1-2209072238
    - threadpoolctl==3.0.0
    - tiktoken==0.7.0
    - tokenizers==0.19.1
    - torch==1.13.0
    - torch-geometric==2.4.0
    - torchaudio==0.13.0
    - torchdata==0.7.1
    - torchmetrics==1.4.0.post0
    - torchtime==0.5.1
    - torchvision==0.11.2+cu102
    - tornado==6.4
    - tqdm==4.64.1
    - traitlets==5.14.2
    - transformers==4.43.3
    - transformers-stream-generator==0.0.5
    - tsai==0.3.9
    - tsfresh==0.20.2
    - typer==0.9.0
    - typing-extensions==4.10.0
    - unrar==0.4
    - utils==1.0.1
    - wandb==0.16.6
    - wasabi==1.1.2
    - wcwidth==0.2.6
    - weasel==0.3.4
    - werkzeug==3.0.1
    - wget==3.2
    - wrapt==1.14.1
    - xlwt==1.3.0
    - yarl==1.9.4
    - zipp==3.17.0
prefix: D:\Softwares\anaconda\envs\pytorch_gpu
